import { Restaurant, Category, Dish } from "@/types";

export const mockRestaurant: Restaurant = {
  id: "1",
  name: "Umami Lab",
  slug: "umami-lab",
  description: "Ramen artesanal com sabores autênticos",
  logo_url: null,
  cover_url: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=1200&h=600&fit=crop",
  currency: "EUR",
  languages: ["pt", "en", "es"],
  created_at: "2026-01-01",
};

export const mockCategories: Category[] = [
  { id: "c1", restaurant_id: "1", name: "Entradas", name_en: "Starters", name_es: "Entrantes", sort_order: 1, created_at: "" },
  { id: "c2", restaurant_id: "1", name: "Ramen Classic", name_en: "Classic Ramen", name_es: "Ramen Clásico", sort_order: 2, created_at: "" },
  { id: "c3", restaurant_id: "1", name: "Ramen Especial", name_en: "Specialty Ramen", name_es: "Ramen Especial", sort_order: 3, created_at: "" },
  { id: "c4", restaurant_id: "1", name: "Sobremesas", name_en: "Desserts", name_es: "Postres", sort_order: 4, created_at: "" },
];

export const mockDishes: Dish[] = [
  {
    id: "d1",
    restaurant_id: "1",
    category_id: "c1",
    name: "Gyoza de Porco",
    name_en: "Pork Gyoza",
    name_es: "Gyoza de Cerdo",
    description: "Dumplings japoneses recheados com porco, grelhados até ficarem crocantes. Servidos com molho de soja e vinagre de arroz.",
    description_en: "Japanese dumplings filled with pork, grilled until crispy. Served with soy sauce and rice vinegar.",
    description_es: "Empanadillas japonesas rellenas de cerdo, a la plancha hasta quedar crujientes. Servidas con salsa de soja y vinagre de arroz.",
    price: 6.50,
    image_url: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&h=600&fit=crop",
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: false,
    is_popular: true,
    is_spicy: false,
    allergens: ["gluten", "soja"],
    sort_order: 1,
    created_at: "",
  },
  {
    id: "d2",
    restaurant_id: "1",
    category_id: "c1",
    name: "Edamame",
    name_en: "Edamame",
    name_es: "Edamame",
    description: "Soja verde cozida no vapor com flor de sal. Simples e deliciosa.",
    description_en: "Steamed green soybeans with sea salt. Simple and delicious.",
    description_es: "Soja verde cocida al vapor con sal marina. Simple y deliciosa.",
    price: 4.00,
    image_url: "https://images.unsplash.com/photo-1536856136534-bb679c52a9aa?w=600&h=600&fit=crop",
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    is_popular: false,
    is_spicy: false,
    allergens: ["soja"],
    sort_order: 2,
    created_at: "",
  },
  {
    id: "d3",
    restaurant_id: "1",
    category_id: "c2",
    name: "Shoyu Ramen",
    name_en: "Shoyu Ramen",
    name_es: "Shoyu Ramen",
    description: "Caldo à base de soja, chashu pork, ovo mollete, cebolinho e rebentos de bambu. O clássico intemporal.",
    description_en: "Soy-based broth, chashu pork, soft-boiled egg, scallions and bamboo shoots. The timeless classic.",
    description_es: "Caldo a base de soja, chashu de cerdo, huevo mollet, cebolleta y brotes de bambú. El clásico atemporal.",
    price: 12.50,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=600&fit=crop",
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: false,
    is_popular: true,
    is_spicy: false,
    allergens: ["gluten", "ovos", "soja"],
    sort_order: 1,
    created_at: "",
  },
  {
    id: "d4",
    restaurant_id: "1",
    category_id: "c2",
    name: "Miso Ramen",
    name_en: "Miso Ramen",
    name_es: "Miso Ramen",
    description: "Caldo rico de miso, carne de porco moída, milho doce, manteiga e cebolinho. Conforto em cada colherada.",
    description_en: "Rich miso broth, ground pork, sweet corn, butter and scallions. Comfort in every spoonful.",
    description_es: "Caldo rico de miso, carne de cerdo picada, maíz dulce, mantequilla y cebolleta. Conforto en cada cucharada.",
    price: 13.00,
    image_url: "https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=600&h=600&fit=crop",
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: false,
    is_popular: true,
    is_spicy: false,
    allergens: ["gluten", "soja", "lácteos"],
    sort_order: 2,
    created_at: "",
  },
  {
    id: "d5",
    restaurant_id: "1",
    category_id: "c2",
    name: "Tonkotsu Ramen",
    name_en: "Tonkotsu Ramen",
    name_es: "Tonkotsu Ramen",
    description: "Caldo cremoso de ossos de porco cozidos 12h, chashu, óleo de alho negro e ovo marinado. Intenso e sedoso.",
    description_en: "Creamy pork bone broth simmered for 12h, chashu, black garlic oil and marinated egg. Intense and silky.",
    description_es: "Caldo cremoso de huesos de cerdo cocido 12h, chashu, aceite de ajo negro y huevo marinado. Intenso y sedoso.",
    price: 14.50,
    image_url: "https://images.unsplash.com/photo-1614563637806-1d0e645e0940?w=600&h=600&fit=crop",
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: false,
    is_popular: true,
    is_spicy: false,
    allergens: ["gluten", "ovos", "soja"],
    sort_order: 3,
    created_at: "",
  },
  {
    id: "d6",
    restaurant_id: "1",
    category_id: "c2",
    name: "Shio Ramen",
    name_en: "Shio Ramen",
    name_es: "Shio Ramen",
    description: "Caldo leve de sal, frango grelhado, rebentos de bambu e nori. A escolha mais leve e delicada.",
    description_en: "Light salt broth, grilled chicken, bamboo shoots and nori. The lightest and most delicate choice.",
    description_es: "Caldo ligero de sal, pollo a la plancha, brotes de bambú y nori. La elección más ligera y delicada.",
    price: 12.00,
    image_url: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=600&h=600&fit=crop",
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: false,
    is_popular: false,
    is_spicy: false,
    allergens: ["gluten"],
    sort_order: 4,
    created_at: "",
  },
  {
    id: "d7",
    restaurant_id: "1",
    category_id: "c3",
    name: "Spicy Tan Tanmen",
    name_en: "Spicy Tan Tanmen",
    name_es: "Tan Tanmen Picante",
    description: "Caldo de gergelim com chili, porco moído picante, bok choy e amendoim moído. Um abraço picante.",
    description_en: "Sesame broth with chili, spicy ground pork, bok choy and crushed peanuts. A spicy hug.",
    description_es: "Caldo de sésamo con chili, cerdo picado picante, bok choy y cacahuetes triturados. Un abrazo picante.",
    price: 15.00,
    image_url: "https://images.unsplash.com/photo-1470324161839-ce2bb6fa6bc3?w=600&h=600&fit=crop",
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: false,
    is_popular: true,
    is_spicy: true,
    allergens: ["gluten", "soja", "amendoim"],
    sort_order: 1,
    created_at: "",
  },
  {
    id: "d8",
    restaurant_id: "1",
    category_id: "c3",
    name: "Black Garlic Ramen",
    name_en: "Black Garlic Ramen",
    name_es: "Ramen de Ajo Negro",
    description: "Base tonkotsu, óleo de alho negro torrado, chalotas crocantes e ovo mollete. Umami profundo.",
    description_en: "Tonkotsu base, roasted black garlic oil, crispy shallots and soft egg. Deep umami.",
    description_es: "Base tonkotsu, aceite de ajo negro tostado, chalotas crujientes y huevo mollet. Umami profundo.",
    price: 15.50,
    image_url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=600&h=600&fit=crop",
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: false,
    is_popular: true,
    is_spicy: false,
    allergens: ["gluten", "ovos", "soja"],
    sort_order: 2,
    created_at: "",
  },
  {
    id: "d9",
    restaurant_id: "1",
    category_id: "c3",
    name: "Vegan Miso Ramen",
    name_en: "Vegan Miso Ramen",
    name_es: "Ramen Miso Vegano",
    description: "Caldo de miso vegetal, tofu grelhado, shiitake, milho e bok choy. Saboroso e 100% plant-based.",
    description_en: "Vegetable miso broth, grilled tofu, shiitake, corn and bok choy. Flavorful and 100% plant-based.",
    description_es: "Caldo de miso vegetal, tofu a la plancha, shiitake, maíz y bok choy. Sabroso y 100% vegetal.",
    price: 13.50,
    image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&h=600&fit=crop",
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    is_popular: false,
    is_spicy: false,
    allergens: ["gluten", "soja"],
    sort_order: 3,
    created_at: "",
  },
  {
    id: "d10",
    restaurant_id: "1",
    category_id: "c4",
    name: "Mochi de Matcha",
    name_en: "Matcha Mochi",
    name_es: "Mochi de Matcha",
    description: "Bolinhos de arroz glutinoso recheados com gelado de matcha. Textura macia e sabor intenso.",
    description_en: "Glutinous rice cakes filled with matcha ice cream. Soft texture and intense flavor.",
    description_es: "Pasteles de arroz glutinoso rellenos de helado de matcha. Textura suave y sabor intenso.",
    price: 5.50,
    image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&h=600&fit=crop",
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    is_popular: true,
    is_spicy: false,
    allergens: ["lácteos"],
    sort_order: 1,
    created_at: "",
  },
  {
    id: "d11",
    restaurant_id: "1",
    category_id: "c4",
    name: "Dorayaki",
    name_en: "Dorayaki",
    name_es: "Dorayaki",
    description: "Panquecas japonesas recheadas com pasta de feijão azuki doce. Clássico doce japonês.",
    description_en: "Japanese pancakes filled with sweet azuki bean paste. Classic Japanese sweet.",
    description_es: "Panqueques japoneses rellenos de pasta de judías azuki dulce. Clásico dulce japonés.",
    price: 4.50,
    image_url: "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=600&h=600&fit=crop",
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    is_popular: false,
    is_spicy: false,
    allergens: ["gluten"],
    sort_order: 2,
    created_at: "",
  },
];

export function getMockData() {
  return {
    restaurant: mockRestaurant,
    categories: mockCategories,
    dishes: mockDishes,
  };
}
